#!/bin/sh
set -e
test -n "$BASH_DASHX" && set -x

# This script is based on the work of Rob Muhlestein (@rwxrob).
# See his scripts/zet at: https://github.com/rwxrob/dot/

#ln -sf "$PWD/bashrc" "$HOME/.bashrc"
#ln -sf "$PWD/shell.d" "$HOME/.shell.d"
#ln -sf "$PWD/dircolors" "$HOME/.dircolors"
#ln -sf "$PWD/inputrc" "$HOME/.inputrc"
#ln -sf "$PWD/profile" "$HOME/.profile"

#mkdir -p "$HOME/.local/bin" || true

mkdir ~/.config/ 2>/dev/null || true

cp ~/.dotfiles/shell.d/config-default.sh ~/.config/dotfiles/config.sh

for i in simple-zet vim; do
  cd $i && ./setup
  cd -
done

