#!/bin/sh

#rm -rf ~/.dotfiles/scripts/simple-zet 2>/dev/null
rm ~/.dotfiles/scripts/simple-zet 2>/dev/null

#git clone --depth 1 --branch master https://github.com/vmarquezh/simple-zet.git ~/.dotfiles/scripts/simple-zet
ln -s ~/simple-zet ~/.dotfiles/scripts/simple-zet

~/.dotfiles/scripts/simple-zet/setup

