#!/bin/sh

# Shows a list of subtrees added to the Git repo on the current directory.
#
# As of today, Git does not have a command to show or list subtrees. this
# script greps a `git log` looking for entries containing 'git-subtree-dir';
# then produces a list of unique and sorted matches which is used to
# `git rev-parse` to find the corresponding paths within the project.

git log | grep git-subtree-dir | tr -d ' ' | cut -d ':' -f2 | sort | uniq | xargs -I {} bash -c 'if [ -d $(git rev-parse --show-toplevel)/{} ] ; then echo {}; fi'

# TODO: This is for --all
#git log | grep git-subtree-dir | tr -d ' ' | cut -d ':' -f2 | sort | uniq

