#!/bin/bash

DIR=""
FLE=""
ACTIONMSG="Changed"
MSG=""
COMMITS="NO"

test "$1" == "--commit" && ACTIONMSG="Committing"

doCommit() {
  MSG=$(head -1 "$FLE" | sed 's/#\+ *//')
  echo "$ACTIONMSG ($CHGTYPE): $DIR - $MSG"
  if test "$ACTIONMSG" == "Committing"; then
    git add -A "$DIR"
    git commit -m "$MSG" > /dev/null
    COMMITS="YES"
  fi
}

CHANGES="$(git status --porcelain | sort -b -k 2)"

while read -r CHGTYPE CHANGE; do
  DIR="$(echo "$CHANGE" | cut -c1-14)/"
  FLE="$DIR""README.md"
  if test "$CHGTYPE" == "??"; then      # New file (could be != README.md)
    TYPEMSG="New......"
  elif test "$CHGTYPE" == "M"; then     # File modified (could be != README.md)
    TYPEMSG="Changes.:"
  elif test "$CHGTYPE" == "D"; then     # File deleted.
    TYPEMSG="Removals:"
  fi
  echo "$TYPEMSG $DIR - $CHANGE"
done < <(printf '%s\n' "$CHANGES")

if test "$COMMITS" == "YES"; then
  echo "Commits done. Remember to push changes to central repository."
fi

