#!/bin/bash

if test -r "~/.config/dotfiles/config"; then
    source ~/.config/dotfiles/config
else
    echo "Dotfiles configuration file does not exist (~/.config/dotfiles/config)."
    echo "Some things from Dotfiles maight not work."
fi

# Sometimes I source ~/.bashrc or this file fir debugging.
# This validations avoids polluting PATH.
if [[ ! "$PATH" == *".dotfiles/scripts"* ]]; then
    PATH="~/.dotfiles/scripts/${PATH:+:${PATH}}"
    export PATH
fi

