#!/bin/bash

if test -r ~/.config/dotfiles/config.sh; then
    test -z "$GITUSER" && source ~/.config/dotfiles/config.sh
else
    echo "Dotfiles configuration file does not exist (~/.config/dotfiles/config.sh)."
    echo "Some things from Dotfiles may not work."
fi

# Sometimes I source ~/.bashrc or this file for debugging.
# This validations avoids polluting PATH.
if [[ ! "$PATH" == *".dotfiles/scripts"* ]]; then
    PATH="~/.dotfiles/scripts/${PATH:+:${PATH}}"
    export PATH
fi

test -r ~/.dotfiles/shell.d/bash_aliases && source ~/.dotfiles/shell.d/bash_aliases

